---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.hello-app: glob:prod-*
  labels:
    app: hello-app
  name: hello-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: mareimorsy/hello-app:prod-3
        imagePullPolicy: IfNotPresent
        name: hello-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
