apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
  name: hello-app
  namespace: default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: hello-app
  type: ClusterIP